[phases.setup]
nixPkgs = ["php81", "php81Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --no-interaction"
]

[phases.build]
cmds = [
  "chmod -R 777 storage bootstrap/cache",
  "php artisan key:generate",
  "php artisan config:cache"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
